### ISSUE TITLE
How should I return a custom error message?

### ISSUE THREAD

**Issue by JornVernee** [jon-hanson/parsecj#3]
I have this parser that parses symbols, but when a symbol is not in my symbol table, I want to return an error message.

	Parser<Character, T> symbol
		= alphaNum.bind(str -> 
			symbols.containsKey(str) 
				? retn(symbols.get(str))
				: fail()
		);

The only way I could find to do this is with `fail()`. But it returns the message:

    Unexpected 'null' at position 3. Expecting one of []

Which is not very informative.

I want to return something like:

    Unknown symbol "bla" at position 3.

There seems to be no way to do this.

**Comment by jon-hanson** [comment]
I've checked in a [change](https://github.com/jon-hanson/parsecj/commit/65fc039cb3bc8c213f21a8fcff97c2586e30c531) which adds an overload for fail() which accepts a String msg parameter. In the event fail(msg) is invoked it should yield an error message of the form:

`<msg> at position x`

where <msg> is your supplied msg String.

Can you give that a try and let me know if it what you're after.

**Comment by JornVernee** [comment]
Thanks for the quick response!

That is exactly what I was looking for.

The result looks like this:

	Parser<Character, T> symbol
		= alphaNum.bind(str -> 
			symbols.containsKey(str) 
				? retn(symbols.get(str))
				: fail(String.format("Unknown symbol: '%s'", str))
		);

The program is a pretty simple logical expression evaluator, so I just hard coded the message here.

I'm still trying to see if I can get the position to point to the beginning of the symbol somehow (position 3 is the last character).

**Comment by jon-hanson** [comment]
Could you use the `or `combinator for this, e.g.:

`or(attempt(symbol), fail("msg"))`

**Comment by JornVernee** [comment]
I thought about that, but you would no be able to include the symbol that was parsed in the message.

**Comment by jon-hanson** [comment]
I think the problem here is that a parsing failure in this style of parser simply means it backtracks and tries the next alternative - it's not necessarily an outright error. But in your case it seems that what you really want is for the parser to completely stop and issue an error.

To put it another way, the fact the parser has correctly parsed a symbol, which then isn't found in a lookup table, is really an evaluation error rather than a syntax error. The two seem conflated because you're evaluating the expression while parsing it.

As such, I don't think there is a simple way to extend ParsecJ to handle this, because it's not a parsing issue. One obvious workaround is for you to throw an exception when the lookup fails. It still doesn't give you the location of the error, but that's in part due to the fact that the error occurs during evaluation not parsing.

**Comment by JornVernee** [comment]
I understand. I guess I would have to creating some AST first and then evaluate that again to see if all the symbols can be found.

 Throwing an exception won't work, since it's inside of a lambda.

I just asked about that solution, since I seem to remember something similar existing in FParsec.

**Comment by jon-hanson** [comment]
You can throw an unchecked exception (i.e. RuntimeException or subclass thereof) from a lambda.

Failing that, then parsing into an AST, and then evaluating the AST as a separate step, as you suggest, would be the approach I too would favour.

I had a look at the Haskell Parsec, to see if it had a combinator which would work here, but as far as I can see it doesn't, most likely for the reasons I outlined above.
