### ISSUE TITLE
Parser fails even if input is correct

### ISSUE THREAD

**Issue by bkolasa** [jon-hanson/parsecj#5]
Consider following piece of code.

        Parser<Character, String> drop = Text.string("drop");
        Parser<Character, String> describe = Text.string("describe");
        Parser<Character, String> choice = drop.or(describe);
        Reply<Character, String> reply = choice.parse(State.of("describe"));
        System.out.println(reply.getMsg()); 

We have here a parser that should succeed either for string starting with "drop" or "describe". However, it fails for input "describe" with following error:

       Unexpected 'e' at position 1. Expecting one of ["drop"]

It is not a correct behaviour, isn't it?

**Comment by jon-hanson** [comment]
The problem here is that ParsecJ (and it's ancestor Parsec) is not a backtracking parser. In your grammar, both "drop" and "describe" begin with "d", but since the `drop` rule is first it takes precedence. What that means is that when parsing your input ("describe"), once the `drop` rule consumes the "d" character it will not backtrack when it subsequently it fails (when it encounters the "r").

This is by design, and is covered in the original Parsec paper, but is basically done for performance reasons.

However you can override this behaviour, at the rule level, by wrapping a parser in an `attempt` combinator:

 ```
        Parser<Character, String> drop = attempt(Text.string("drop"));
        Parser<Character, String> describe = Text.string("describe");
        Parser<Character, String> choice = drop.or(describe);
        Reply<Character, String> reply = choice.bind(s -> retn(s)).parse(Input.of("describe"));
        System.out.println(reply.getResult());
```

This instructs the parser to backtrack to where it was before it started applying the parser inside the `attempt` combinator, in this case back to the beginning of the "describe" string, allowing it to then successfully apply the `describe` rule.
